# Generated by Django 4.2.3 on 2023-08-01 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55d2cbb6-c10e-4166-b72a-61a33be130ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
