# Generated by Django 4.2.3 on 2023-08-01 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4f1c3c1-35f7-4d09-b1c9-dbf1038f6e3a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
