# Generated by Django 4.2.3 on 2023-07-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_id_alter_customuser_tmp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tmp_id',
            new_name='id',
        ),
    ]
