# Generated by Django 4.2.3 on 2023-08-01 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68d869e1-4eff-40bc-9446-aed1a93b3ce8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
