# Generated by Django 4.2.3 on 2023-08-01 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('993eb1a4-7bfc-41e4-b989-795e53a30aac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
