# Generated by Django 4.2.3 on 2023-08-01 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_age_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3ac4afe6-cb57-41d3-8a8e-fc18ed06417c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
