# Generated by Django 4.2.3 on 2023-08-01 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_age_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f41de8c2-2edc-4553-8c4e-a1e008d9337d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
