# Generated by Django 4.2.3 on 2023-08-05 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d6b54429-0a7d-4994-a672-bf8f3694047e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
