# Generated by Django 4.2.3 on 2023-08-05 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0987ab8c-b803-4f60-af9d-a46fee6c0aa2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
