# you can specify version, but it is optional

# tell docker what kind of services this app has and how to build them
services:
  web:
    build: . # where can we find the Dockerfile. each service may have their own Dockerfile
    volumes: 
      - .:/code # /code will "sync" with file we are working in (App folder)
    ports:
      - "8000:8000"
    depends_on: # db will load first before web service
      - db
  
  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:


