# Generated by Django 4.2.3 on 2023-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
