# Generated by Django 4.2.3 on 2023-08-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_time_created_schedule_time_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
